Use google_search not google_search_retrieval (#39)
Google recommended using the google_search field instead of google_search_retrieval. I don't know if it's only for experimental models.

 llm -m gemini-2.0-flash-exp -o google_search 1   'What is the latest version of pydantic?'

Error: Unable to submit request because Please use google_search field instead of google_search_retrieval field.. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/gemini